name: Build and test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cfg:
          - { BUILD_TYPE: release }
          - { BUILD_TYPE: debug }
          - { BUILD_TYPE: asan }
        include:
          - gcc: 13
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install "gcc-${{ matrix.gcc }}" "g++-${{ matrix.gcc }}" cmake build-essential -y
        shell: bash
      - name: Set gcc version
        run: |
          echo "CC=gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.gcc }}" >> $GITHUB_ENV
      - name: Install conan
        run: pip3 install conan==2.3.0 --upgrade --break-system-packages
        shell: bash
      - name: Download dependencies
        working-directory: ./cpp-fs
        run: make prepare-${{ matrix.cfg.BUILD_TYPE }}
      - name: Build
        working-directory: ./cpp-fs
        run: make ${{ matrix.cfg.BUILD_TYPE }}
      - name: Test
        working-directory: ./cpp-fs
        run: make ${{ matrix.cfg.BUILD_TYPE }}-test
